function [Status] = svm_training()
File=load('speech');
%==================Normal======================================%
%------------------Angry----------------------------------------
rng(10);
Features=[File.features(1:6,:);File.features(13:18,:)];
N_Angry_N_Happy=[File.categories(1:6,1);File.categories(13:18,1)];
SVMStruct_N_Angry_N_Happy= fitcsvm(Features,N_Angry_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_N_Happy','-append');
rng(10);
Features=[File.features(1:6,:);File.features(25:30,:)];
N_Angry_N_Neutral=[File.categories(1:6,1);File.categories(25:30,1)];
SVMStruct_N_Angry_N_Neutral= fitcsvm(Features,N_Angry_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_N_Neutral','-append');
rng(10);
Features=[File.features(1:6,:);File.features(37:42,:)];
N_Angry_N_Sad=[File.categories(1:6,1);File.categories(37:42,1)];
SVMStruct_N_Angry_N_Sad= fitcsvm(Features,N_Angry_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_N_Sad','-append');

rng(10);
Features=[File.features(1:6,:);File.features(7:12,:)];
N_Angry_S_Angry=[File.categories(1:6,1);File.categories(7:12,1)];
SVMStruct_N_Angry_S_Angry= fitcsvm(Features,N_Angry_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_S_Angry','-append');
rng(10);
Features=[File.features(1:6,:);File.features(19:24,:)];
N_Angry_S_Happy=[File.categories(1:6,1);File.categories(19:24,1)];
SVMStruct_N_Angry_S_Happy= fitcsvm(Features,N_Angry_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_S_Happy','-append');
rng(10);
Features=[File.features(1:6,:);File.features(31:36,:)];
N_Angry_S_Neutral=[File.categories(1:6,1);File.categories(31:36,1)];
SVMStruct_N_Angry_S_Neutral= fitcsvm(Features,N_Angry_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_S_Neutral','-append');
rng(10);
Features=[File.features(1:6,:);File.features(43:46,:)];
N_Angry_S_Sad=[File.categories(1:6,1);File.categories(43:46,1)];
SVMStruct_N_Angry_S_Sad= fitcsvm(Features,N_Angry_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Angry_S_Sad','-append');
%------------------Happy----------------------------------------
rng(10);
Features=[File.features(13:18,:);File.features(1:6,:)];
N_Happy_N_Angry=[File.categories(13:18,1);File.categories(1:6,1)];
SVMStruct_N_Happy_N_Angry= fitcsvm(Features,N_Happy_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_N_Angry','-append');
rng(10);
Features=[File.features(13:18,:);File.features(25:30,:)];
N_Happy_N_Neutral=[File.categories(13:18,1);File.categories(25:30,1)];
SVMStruct_N_Happy_N_Neutral= fitcsvm(Features,N_Happy_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_N_Neutral','-append');
rng(10);
Features=[File.features(13:18,:);File.features(37:42,:)];
N_Happy_N_Sad=[File.categories(13:18,1);File.categories(37:42,1)];
SVMStruct_N_Happy_N_Sad= fitcsvm(Features,N_Happy_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_N_Sad','-append');

rng(10);
Features=[File.features(13:18,:);File.features(7:12,:)];
N_Happy_S_Angry=[File.categories(13:18,1);File.categories(7:12,1)];
SVMStruct_N_Happy_S_Angry= fitcsvm(Features,N_Happy_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_S_Angry','-append');
rng(10);
Features=[File.features(13:18,:);File.features(19:24,:)];
N_Happy_S_Happy=[File.categories(13:18,1);File.categories(19:24,1)];
SVMStruct_N_Happy_S_Happy= fitcsvm(Features,N_Happy_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_S_Happy','-append');
rng(10);
Features=[File.features(13:18,:);File.features(31:36,:)];
N_Happy_S_Neutral=[File.categories(13:18,1);File.categories(31:36,1)];
SVMStruct_N_Happy_S_Neutral= fitcsvm(Features,N_Happy_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_S_Neutral','-append');
rng(10);
Features=[File.features(13:18,:);File.features(43:46,:)];
N_Happy_S_Sad=[File.categories(13:18,1);File.categories(43:46,1)];
SVMStruct_N_Happy_S_Sad= fitcsvm(Features,N_Happy_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Happy_S_Sad','-append');

%------------------Neutral----------------------------------------
rng(10);
Features=[File.features(25:30,:);File.features(1:6,:)];
N_Neutral_N_Angry=[File.categories(25:30,1);File.categories(1:6,1)];
SVMStruct_N_Neutral_N_Angry= fitcsvm(Features,N_Neutral_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_N_Angry','-append');
rng(10);
Features=[File.features(25:30,:);File.features(13:18,:)];
N_Neutral_N_Happy=[File.categories(13:18,1);File.categories(13:18,1)];
SVMStruct_N_Neutral_N_Happy= fitcsvm(Features,N_Neutral_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_N_Happy','-append');
rng(10);
Features=[File.features(25:30,:);File.features(37:42,:)];
N_Neutral_N_Sad=[File.categories(25:30,1);File.categories(37:42,1)];
SVMStruct_N_Neutral_N_Sad= fitcsvm(Features,N_Neutral_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_N_Sad','-append');

rng(10);
Features=[File.features(25:30,:);File.features(7:12,:)];
N_Neutral_S_Angry=[File.categories(25:30,1);File.categories(7:12,1)];
SVMStruct_N_Neutral_S_Angry= fitcsvm(Features,N_Neutral_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_S_Angry','-append');
rng(10);
Features=[File.features(25:30,:);File.features(19:24,:)];
N_Neutral_S_Happy=[File.categories(25:30,1);File.categories(19:24,1)];
SVMStruct_N_Neutral_S_Happy= fitcsvm(Features,N_Neutral_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_S_Happy','-append');
rng(10);
Features=[File.features(25:30,:);File.features(31:36,:)];
N_Neutral_S_Neutral=[File.categories(25:30,1);File.categories(31:36,1)];
SVMStruct_N_Neutral_S_Neutral= fitcsvm(Features,N_Neutral_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_S_Neutral','-append');
rng(10);
Features=[File.features(25:30,:);File.features(43:46,:)];
N_Neutral_S_Sad=[File.categories(25:30,1);File.categories(43:46,1)];
SVMStruct_N_Neutral_S_Sad= fitcsvm(Features,N_Neutral_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Neutral_S_Sad','-append');
%------------------Sad----------------------------------------
rng(10);
Features=[File.features(37:42,:);File.features(1:6,:)];
N_Sad_N_Angry=[File.categories(25:30,1);File.categories(1:6,1)];
SVMStruct_N_Sad_N_Angry= fitcsvm(Features,N_Sad_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_N_Angry','-append');
rng(10);
Features=[File.features(37:42,:);File.features(13:18,:)];
N_Sad_N_Happy=[File.categories(13:18,1);File.categories(13:18,1)];
SVMStruct_N_Sad_N_Happy= fitcsvm(Features,N_Sad_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_N_Happy','-append');
rng(10);
Features=[File.features(37:42,:);File.features(25:30,:)];
N_Sad_N_Neutral=[File.categories(37:42,1);File.categories(25:30,1)];
SVMStruct_N_Sad_N_Neutral= fitcsvm(Features,N_Sad_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_N_Neutral','-append');

rng(10);
Features=[File.features(37:42,:);File.features(7:12,:)];
N_Sad_S_Angry=[File.categories(37:42,1);File.categories(7:12,1)];
SVMStruct_N_Sad_S_Angry= fitcsvm(Features,N_Sad_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_S_Angry','-append');
rng(10);
Features=[File.features(37:42,:);File.features(19:24,:)];
N_Sad_S_Happy=[File.categories(37:42,1);File.categories(19:24,1)];
SVMStruct_N_Sad_S_Happy= fitcsvm(Features,N_Sad_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_S_Happy','-append');
rng(10);
Features=[File.features(37:42,:);File.features(31:36,:)];
N_Sad_S_Neutral=[File.categories(37:42,1);File.categories(31:36,1)];
SVMStruct_N_Sad_S_Neutral= fitcsvm(Features,N_Sad_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_S_Neutral','-append');
rng(10);
Features=[File.features(37:42,:);File.features(43:46,:)];
N_Sad_S_Sad=[File.categories(37:42,1);File.categories(43:46,1)];
SVMStruct_N_Sad_S_Sad= fitcsvm(Features,N_Sad_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_N_Sad_S_Sad','-append');
%===============================Special==================================%
%------------------Angry----------------------------------------
rng(10);
Features=[File.features(7:12,:);File.features(19:24,:)];
S_Angry_S_Happy=[File.categories(7:12,1);File.categories(19:24,1)];
SVMStruct_S_Angry_S_Happy= fitcsvm(Features,S_Angry_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_S_Happy','-append');
rng(10);
Features=[File.features(7:12,:);File.features(31:36,:)];
S_Angry_S_Neutral=[File.categories(7:12,1);File.categories(31:36,1)];
SVMStruct_S_Angry_S_Neutral= fitcsvm(Features,S_Angry_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_S_Neutral','-append');
rng(10);
Features=[File.features(7:12,:);File.features(43:46,:)];
S_Angry_S_Sad=[File.categories(7:12,1);File.categories(43:46,1)];
SVMStruct_S_Angry_S_Sad= fitcsvm(Features,S_Angry_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_S_Sad','-append');

rng(10);
Features=[File.features(7:12,:);File.features(1:6,:)];
S_Angry_N_Angry=[File.categories(7:12,1);File.categories(1:6,1)];
SVMStruct_S_Angry_N_Angry= fitcsvm(Features,S_Angry_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_N_Angry','-append');
rng(10);
Features=[File.features(7:12,:);File.features(13:18,:)];
S_Angry_N_Happy=[File.categories(7:12,1);File.categories(13:18,1)];
SVMStruct_S_Angry_N_Happy= fitcsvm(Features,S_Angry_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_N_Happy','-append');
rng(10);
Features=[File.features(7:12,:);File.features(25:30,:)];
S_Angry_N_Neutral=[File.categories(7:12,1);File.categories(25:30,1)];
SVMStruct_S_Angry_N_Neutral= fitcsvm(Features,S_Angry_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_N_Neutral','-append');
rng(10);
Features=[File.features(7:12,:);File.features(37:42,:)];
S_Angry_N_Sad=[File.categories(7:12,1);File.categories(37:42,1)];
SVMStruct_S_Angry_N_Sad= fitcsvm(Features,S_Angry_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Angry_N_Sad','-append');
%------------------Happy----------------------------------------
rng(10);
Features=[File.features(19:24,:);File.features(7:12,:)];
S_Happy_S_Angry=[File.categories(19:24,1);File.categories(7:12,1)];
SVMStruct_S_Happy_S_Angry= fitcsvm(Features,S_Happy_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_S_Angry','-append');
rng(10);
Features=[File.features(19:24,:);File.features(31:36,:)];
S_Happy_S_Neutral=[File.categories(19:24,1);File.categories(31:36,1)];
SVMStruct_S_Happy_S_Neutral= fitcsvm(Features,S_Happy_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_S_Neutral','-append');
rng(10);
Features=[File.features(19:24,:);File.features(43:46,:)];
S_Happy_S_Sad=[File.categories(19:24,1);File.categories(43:46,1)];
SVMStruct_S_Happy_S_Sad= fitcsvm(Features,S_Happy_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_S_Sad','-append');

rng(10);
Features=[File.features(19:24,:);File.features(1:6,:)];
S_Happy_N_Angry=[File.categories(19:24,1);File.categories(1:6,1)];
SVMStruct_S_Happy_N_Angry= fitcsvm(Features,S_Happy_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_N_Angry','-append');
rng(10);
Features=[File.features(19:24,:);File.features(13:18,:)];
S_Happy_N_Happy=[File.categories(19:24,1);File.categories(13:18,1)];
SVMStruct_S_Happy_N_Happy= fitcsvm(Features,S_Happy_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_N_Happy','-append');
rng(10);
Features=[File.features(19:24,:);File.features(25:30,:)];
S_Happy_N_Neutral=[File.categories(19:24,1);File.categories(25:30,1)];
SVMStruct_S_Happy_N_Neutral= fitcsvm(Features,S_Happy_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_N_Neutral','-append');
rng(10);
Features=[File.features(19:24,:);File.features(37:42,:)];
S_Happy_N_Sad=[File.categories(19:24,1);File.categories(37:42,1)];
SVMStruct_S_Happy_N_Sad= fitcsvm(Features,S_Happy_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Happy_N_Sad','-append');
%------------------Neutral----------------------------------------
rng(10);
Features=[File.features(31:36,:);File.features(7:12,:)];
S_Neutral_S_Angry=[File.categories(31:36,1);File.categories(7:12,1)];
SVMStruct_S_Neutral_S_Angry= fitcsvm(Features,S_Neutral_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_S_Angry','-append');
rng(10);
Features=[File.features(31:36,:);File.features(19:24,:)];
S_Neutral_S_Happy=[File.categories(31:36,1);File.categories(19:24,1)];
SVMStruct_S_Neutral_S_Happy= fitcsvm(Features,S_Neutral_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_S_Happy','-append');
rng(10);
Features=[File.features(31:36,:);File.features(43:46,:)];
S_Neutral_S_Sad=[File.categories(31:36,1);File.categories(43:46,1)];
SVMStruct_S_Neutral_S_Sad= fitcsvm(Features,S_Neutral_S_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_S_Sad','-append');

rng(10);
Features=[File.features(31:36,:);File.features(1:6,:)];
S_Neutral_N_Angry=[File.categories(31:36,1);File.categories(1:6,1)];
SVMStruct_S_Neutral_N_Angry= fitcsvm(Features,S_Neutral_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_N_Angry','-append');
rng(10);
Features=[File.features(31:36,:);File.features(13:18,:)];
S_Neutral_N_Happy=[File.categories(31:36,1);File.categories(13:18,1)];
SVMStruct_S_Neutral_N_Happy= fitcsvm(Features,S_Neutral_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_N_Happy','-append');
rng(10);
Features=[File.features(31:36,:);File.features(25:30,:)];
S_Neutral_N_Neutral=[File.categories(31:36,1);File.categories(25:30,1)];
SVMStruct_S_Neutral_N_Neutral= fitcsvm(Features,S_Neutral_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_N_Neutral','-append');
rng(10);
Features=[File.features(31:36,:);File.features(37:42,:)];
S_Neutral_N_Sad=[File.categories(31:36,1);File.categories(37:42,1)];
SVMStruct_S_Neutral_N_Sad= fitcsvm(Features,S_Neutral_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Neutral_N_Sad','-append');
%------------------Sad----------------------------------------
rng(10);
Features=[File.features(43:46,:);File.features(7:12,:)];
S_Sad_S_Angry=[File.categories(43:46,1);File.categories(7:12,1)];
SVMStruct_S_Sad_S_Angry= fitcsvm(Features,S_Sad_S_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_S_Angry','-append');
rng(10);
Features=[File.features(43:46,:);File.features(19:24,:)];
S_Sad_S_Happy=[File.categories(43:46,1);File.categories(19:24,1)];
SVMStruct_S_Sad_S_Happy= fitcsvm(Features,S_Sad_S_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_S_Happy','-append');
rng(10);
Features=[File.features(43:46,:);File.features(31:36,:)];
S_Sad_S_Neutral=[File.categories(43:46,1);File.categories(31:36,1)];
SVMStruct_S_Sad_S_Neutral= fitcsvm(Features,S_Sad_S_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_S_Neutral','-append');

rng(10);
Features=[File.features(43:46,:);File.features(1:6,:)];
S_Sad_N_Angry=[File.categories(43:46,1);File.categories(1:6,1)];
SVMStruct_S_Sad_N_Angry= fitcsvm(Features,S_Sad_N_Angry,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_N_Angry','-append');
rng(10);
Features=[File.features(43:46,:);File.features(13:18,:)];
S_Sad_N_Happy=[File.categories(43:46,1);File.categories(13:18,1)];
SVMStruct_S_Sad_N_Happy= fitcsvm(Features,S_Sad_N_Happy,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_N_Happy','-append');
rng(10);
Features=[File.features(43:46,:);File.features(25:30,:)];
S_Sad_N_Neutral=[File.categories(43:46,1);File.categories(25:30,1)];
SVMStruct_S_Sad_N_Neutral= fitcsvm(Features,S_Sad_N_Neutral,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_N_Neutral','-append');
rng(10);
Features=[File.features(43:46,:);File.features(37:42,:)];
S_Sad_N_Sad=[File.categories(43:46,1);File.categories(37:42,1)];
SVMStruct_S_Sad_N_Sad= fitcsvm(Features,S_Sad_N_Sad,'KernelScale','auto','Standardize',true,'OutlierFraction',0.5);
save('svmmodels.mat','SVMStruct_S_Sad_N_Sad','-append');
Status= 'SVM Model has been Trained';